apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/red-hat-data-services/notebooks/tree/main/jupyter/datascience/ubi8-python-3.8"
    opendatahub.io/notebook-image-name: "Standard Data Science"
    opendatahub.io/notebook-image-desc: "Jupyter notebook image with a set of data science libraries that advanced AI/ML notebooks will use as a base image to provide a standard for libraries avialable in all notebooks"
    opendatahub.io/notebook-image-order: "20"
  name: s2i-generic-data-science-notebook
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.8"}]'
      opendatahub.io/notebook-python-dependencies: '[{"name":"Boto3","version":"1.17"},{"name":"Kafka-Python","version":"2.0"},{"name":"Matplotlib","version":"3.4"},{"name":"Numpy","version":"1.19"},{"name":"Pandas","version":"1.2"},{"name":"Scikit-learn","version":"0.24"},{"name":"Scipy","version":"1.6"}]'
      openshift.io/imported-from: quay.io/modh/odh-generic-data-science-notebook
    from:
      kind: DockerImage
      # if you change the image tag, change the "-N" on the tag name immediately below
      name: quay.io/modh/odh-generic-data-science-notebook@sha256:ebb5613e6b53dc4e8efcfe3878b4cd10ccb77c67d12c00d2b8c9d41aeffd7df5
    name: "py3.8-v1"
    referencePolicy:
      type: Source
  - annotations:
      opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.9"}]'
      opendatahub.io/notebook-python-dependencies: '[{"name":"Boto3","version":"1.24"},{"name":"Kafka-Python","version":"2.0"},{"name":"Matplotlib","version":"3.6"},{"name":"Numpy","version":"1.24"},{"name":"Pandas","version":"1.5"},{"name":"Scikit-learn","version":"1.2"},{"name":"Scipy","version":"1.9"}]'
      openshift.io/imported-from: quay.io/rh_ee_atheodor/notebooks
    from:
      kind: DockerImage
      # if you change the image tag, change the "-N" on the tag name immediately below
      name: quay.io/opendatahub/notebooks@sha256:ff2b3bcada32edcfea7694ba65e9c9673195dc1bea067a61708a850e2215dc51
    name: "py3.9-v2"
    referencePolicy:
      type: Source
